version: '3.3'

services:
  db-templates-dev:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017

    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
