#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "-----------------------------------"
echo "auto-formatting code..."
echo "-----------------------------------"

npx nx format:write
git add .

echo "\nYou can now push your code..."
